stages:
    - test-be
    - build-be

test be:
    stage: test-be
    image: golang:1.18
    tags:
        - gcp-shell
    script:
        - echo "testing"
        - go version
        - go test ./... -coverprofile=coverage.out

build be:
    stage: build-be
    image: golang:1.18
    tags:
        - gcp-shell
    script:
        - echo "I am a build image!"
        - docker build ./tode-be



