stages:
    - test-be
    - build-be

test be:
    stage: test-be  
    image: golang:1.18
    tags:
        - gcp-go
    before_script:
        - go version
        - cd todo-be
    script:
        - echo "testing"
        - go test ./... -coverprofile=coverage.out
    artifacts:
      paths:
        - "coverage.out"

build be:
    stage: build-be
    image: docker.io/golang:alpine3.16
    tags:
        - gcp-shell
    before_script:
        - echo $REGISTRY_USER
        - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASSWORD" registry.hub.docker.com
    script:
        - echo "I am a build image!"
        - docker build --pull -t todo-be:latest ./todo-be
        - docker push $REGISTRY_USER/todo-be:latest



