stages:
    - test
    - build

test job:
    stage: test
    tags:
        - golang
    script:
        - echo "I am a unit test!"

build job:
    stage: build
    tags:
        - golang
    script:
        - echo "I am a build image!"

environment echoes:
  stage: build
  tags:
      - golang
  script:
    - echo "Who am I running as..."
    - whoami
    - echo "Where am I..."
    - pwd
    - ls -al
    - echo "Here's what is available in our environment..."
    - env
    - echo "hai"

