stages:
    - testing
    - build

variables:
    REGISTRY_URL: "docker.io"

test be:
    stage: testing
    image: golang:1.18  
    tags:
        - gcp-go
    before_script:
        - go version
        - cd todo-be
    script:
        - echo "testing"
        - go test ./... -coverprofile=coverage.out
    artifacts:
      paths:
        - "coverage.out"
test fe:
    stage: testing 
    image: node:10.15.3
    tags:
        - gcp-go
    before_script:
        - node -v
        - cd todo-fe
    script:
        - echo "testing"
    artifacts:
      paths:
        - "coverage.out"

build be:
    stage: build
    tags:
        - gcp-shell
    only:
        - main
    before_script:
        - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASSWORD" $REGISTRY_URL
    script:
        - echo "I am a build image!"
        - docker build --pull -t "$REGISTRY_USER/todo-be:latest" ./todo-be
        - docker push $REGISTRY_USER/todo-be:latest



