image: golang:1.18

stages:
    - test-be
    - build-be

test be:
    stage: test-be
    tags:
        - gcp-go
    before_script:
        - go version
    script:
        - echo "testing"
        - go test ./... -coverprofile=coverage.out

build be:
    stage: build-be
    image: docker.io/golang:alpine3.16
    tags:
        - gcp-shell
    script:
        - echo "I am a build image!"
        - docker build ./tode-be



