kind: Deployment
apiVersion: apps/v1
metadata:
  name: todo-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      name: todo-fe
  template:
    metadata:
      name: todo-fe
      labels:
        name: todo-fe
    spec:
      containers:
        - name: todo-fe
          image: fadellh/todo-fe:latest
          ports:
            - containerPort: 8000
              protocol: TCP
          env:
            - name: VUE_APP_API_URL
              value: http://localhost:8080
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
---
kind: Service
apiVersion: v1
metadata:
  name: todo-fe-service
spec:
  type: NodePort
  selector:
    name: todo-fe
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30002