kind: Deployment
apiVersion: apps/v1
metadata:
  name: todo-be
spec:
  replicas: 1
  selector:
    matchLabels:
      name: todo-be
  template:
    metadata:
      name: todo-be
      labels:
        name: todo-be
    spec:
      containers:
        - name: todo-be
          image: fadellh/todo-be:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: rahasia
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE
              value: belajar
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
---
kind: Service
apiVersion: v1
metadata:
  name: todo-be-service
spec:
  type: NodePort
  selector:
    name: todo-be
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001